$ErrorActionPreference = 'Stop'
$reelPath     = 'output/uat/UAT_ANNOTATED.mp4'
$mdReceipt    = 'output/R23_DEMO_RECEIPT.md'
$uatJson      = 'output/UAT_STATUS.json'
$pwJson       = 'output/uat-report.json'
$reportIndex  = 'output/playwright-report/index.html'
$serve        = $false  # change to $true to start local server at the end

function Get-JsonSafe($path) {
  if (Test-Path $path) {
    try { return Get-Content $path -Raw | ConvertFrom-Json } catch { return $null }
  }
  return $null
}

function SizeString($bytes) {
  if ($bytes -ge 1MB) { '{0:N1} MB' -f ($bytes/1MB) }
  elseif ($bytes -ge 1KB) { '{0:N1} KB' -f ($bytes/1KB) }
  else { "$bytes B" }
}

# 1) Verify artifacts (existence + minimal health)
if (!(Test-Path $reelPath)) { throw "Missing reel video: $reelPath" }
$reelItem = Get-Item $reelPath
$reelSize = $reelItem.Length
if ($reelSize -lt 300KB) { Write-Warning "Reel size seems small ($reelSize bytes). Proceeding but flagging in receipt." }

if (!(Test-Path $reportIndex)) { Write-Warning "Missing Playwright HTML report at $reportIndex" }

$uat = Get-JsonSafe $uatJson
$pw  = Get-JsonSafe $pwJson

# Build summary numbers from whichever JSON we can read
$exitCode = if ($uat -and $uat.PSObject.Properties.Name -contains 'exit_code') { [int]$uat.exit_code } else { $null }
$pass = $fail = $skip = $total = $null

if ($pw -and $pw.suites) {
  # Playwright JSON reporter shape; count tests by outcome
  $tests = @()
  foreach ($s in $pw.suites) {
    foreach ($sp in $s.suites) {
      foreach ($spec in $sp.specs) {
        foreach ($t in $spec.tests) { $tests += $t }
      }
    }
  }
  $total = $tests.Count
  $pass  = ($tests | Where-Object { $_.results.outcome -contains 'expected' -or $_.results.outcome -contains 'passed' }).Count
  $fail  = ($tests | Where-Object { $_.results.outcome -contains 'unexpected' -or $_.results.outcome -contains 'failed' }).Count
  $skip  = ($tests | Where-Object { $_.results.outcome -contains 'skipped' }).Count
} elseif ($uat) {
  # Fallback—some runs store counts here
  $total = $uat.total     ; $pass  = $uat.passed
  $fail  = $uat.failed    ; $skip  = $uat.skipped
}

# 2) Create receipt (markdown)
New-Item -ItemType Directory -Force -Path (Split-Path $mdReceipt) | Out-Null
$shaShort = (git rev-parse --short HEAD).Trim()
$nowET    = (Get-Date -Format "yyyy-MM-dd HH:mm:ss 'ET'")
$reelSizeStr = SizeString $reelSize
$serveUrl = 'http://127.0.0.1:8000/output/uat/UAT_REEL_V2.mp4'
$reportUrl= 'http://127.0.0.1:8000/output/playwright-report/index.html'

$verdict =
  if ($exitCode -eq 0 -and $reelSize -ge 300KB) { 'PASS' }
  elseif ($exitCode -eq 0 -and $reelSize -lt 300KB) { 'WARN (small reel file)' }
  else { 'PARTIAL (check report/logs)' }

$md = @"
# R2.3 Demo Receipt — Always-Works Reel (Story UI)

**Status:** $verdict
**Date (ET):** $nowET
**Commit:** $shaShort

## Artifacts
- Reel (local): [output/uat/UAT_REEL_V2.mp4](output/uat/UAT_REEL_V2.mp4)  (_$reelSizeStr_)
- Reel (served): <$serveUrl>
- Playwright report (local): [output/playwright-report/index.html](output/playwright-report/index.html)
- Playwright report (served): <$reportUrl>
- UAT JSON: [output/UAT_STATUS.json](output/UAT_STATUS.json)
- UAT Reporter JSON: [output/uat-report.json](output/uat-report.json)

## UAT Summary
- **exit_code:** $exitCode
- **total:** $total  •  **passed:** $pass  •  **failed:** $fail  •  **skipped:** $skip

## Notes
- This receipt was auto-generated by the one-paste script (verifier + commit + tag).
- If the reel is too small, re-run the demo with server + UI active to capture more interaction.
"@

$md | Out-File -FilePath $mdReceipt -Encoding UTF8 -Force
Write-Host "Wrote receipt: $mdReceipt" -ForegroundColor Green

# 3) Commit + tag
git add $mdReceipt
if (Test-Path $reelPath) { git add $reelPath }
if (Test-Path $reportIndex) { git add "output/playwright-report/*" }
if (Test-Path $uatJson) { git add $uatJson }
if (Test-Path $pwJson) { git add $pwJson }

git commit -m "chore(r2.3): demo reel v2 verified; receipt and artifacts updated" | Out-Null
$short = (git rev-parse --short HEAD).Trim()
$tag   = "r2.3-demo-$short"
git tag -a $tag -m "R2.3 Always-Works demo accepted at $nowET"
git push origin HEAD --tags
Write-Host "Committed and tagged: $tag" -ForegroundColor Green

# 4) Optional local server
if ($serve) {
  Write-Host "Starting local server at http://127.0.0.1:8000 ..." -ForegroundColor Cyan
  try {
    # Prefer Python http.server if available
    python --version *> $null 2>&1
    if ($LASTEXITCODE -eq 0) {
      Start-Process -NoNewWindow -FilePath python -ArgumentList "-m http.server 8000"
      Start-Sleep -Seconds 2
      Write-Host "Open: $serveUrl" -ForegroundColor Yellow
    } else {
      # Fallback: open folder
      Invoke-Item (Resolve-Path .)
      Write-Warning "Python not found; opened repo folder instead."
    }
  } catch {
    Write-Warning "Could not start server: $($_.Exception.Message)"
  }
}
